name: mat_lgs
description: Bu proje Bitirme Çalışması dersi kapsamında yapılmıştır.


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_pw_validator: ^1.4.2
  fluttertoast: ^8.1.1
  get_it: ^7.2.0
  provider: ^6.0.4
  popup_card: ^0.1.0
  flutter_countdown_timer: ^4.1.0
  chewie: ^1.3.6
  photo_view: ^0.14.0
  get: ^4.6.3
  stop_watch_timer: ^2.0.0
  flutter_timer_countdown: ^1.0.5
  shared_preferences: ^2.1.1
  video_player: ^2.6.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  # fonts:
  #   - family: ArialBlack
  #     fonts:
  #       - asset: fonts/arial_black.ttf
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tests/
    - assets/videos/
    - assets/newStyleTest/
 
