// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zYCA_TCih7F2PKdQFJ9M9TjqhR3Tsaw',
    appId: '1:53014150788:web:75c06947e9582223e08cd1',
    messagingSenderId: '53014150788',
    projectId: 'matlgs',
    authDomain: 'matlgs.firebaseapp.com',
    storageBucket: 'matlgs.appspot.com',
    measurementId: 'G-8Z23RV73NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjZpNTeCY3HbdpKwj9rlTDeXsU4GBank',
    appId: '1:53014150788:android:84ec3ee039a648e8e08cd1',
    messagingSenderId: '53014150788',
    projectId: 'matlgs',
    storageBucket: 'matlgs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjpFiblHUTHkP6e12AGy_-fT56AHhHa0',
    appId: '1:53014150788:ios:f54375c774158963e08cd1',
    messagingSenderId: '53014150788',
    projectId: 'matlgs',
    storageBucket: 'matlgs.appspot.com',
    androidClientId: '53014150788-0mhu56sh2ouqqcf1iu5a2aocsjt09igu.apps.googleusercontent.com',
    iosClientId: '53014150788-j1pakmucm65uek18oe5ooos1m7tvaj5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.matLgs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcjpFiblHUTHkP6e12AGy_-fT56AHhHa0',
    appId: '1:53014150788:ios:f54375c774158963e08cd1',
    messagingSenderId: '53014150788',
    projectId: 'matlgs',
    storageBucket: 'matlgs.appspot.com',
    androidClientId: '53014150788-0mhu56sh2ouqqcf1iu5a2aocsjt09igu.apps.googleusercontent.com',
    iosClientId: '53014150788-j1pakmucm65uek18oe5ooos1m7tvaj5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.matLgs',
  );
}
